services:
  - type: web
    name: nesiha-bot-sitmsu
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 20
